INSERT INTO program (name, school) VALUES
('Bachelor of Adult Education', 2),
('Bachelor of Agricultural Science with Education', 2),
('Bachelor of Arts in Records and Archives Management (Baram)', 2),
('Bachelor of Arts with Education', 2),
('Bachelor of Arts with Education in Zambian Cultures and Ceremonies', 2),
('Bachelor of Arts with Library and Information Studies', 2),
('Bachelor of Community Empowerment Education', 2),
('Bachelor of Cultural Studies', 2),
('Bachelor of Education (Early Childhood Education)', 2),
('Bachelor of Education (Educational Administration and Management)', 2),
('Bachelor of Education (Educational Administration and Management): 3rd Year Entry', 2),
('Bachelor of Education (Educational Psychology)', 2),
('Bachelor of Education (Environmental Education and Management)', 2),
('Bachelor of Education (Guidance and Counselling)', 2),
('Bachelor of Education (Literacy and Language)', 2),
('Bachelor of Education (Primary Education)', 2),
('Bachelor of Education (Social Sciences)', 2),
('Bachelor of Education (Sociology of Education)', 2),
('Bachelor of Education (Special Education): 1st Year Entry', 2),
('Bachelor of Education (Special Education): 3rd Year Entry', 2),
('Bachelor of Education in Chinese Language Teaching', 2),
('Bachelor of Education in Commerce and Entrepreneurship', 2),
('Bachelor of Education-Secondary (Mathematics and Science)', 2),
('Bachelor of Information and Communication Technologies in Education', 2),
('Bachelor of Science with Education', 2),
('Bachelor of Youth Development and Leadership', 2),
('Diploma in ICTs For In-Service Teachers', 2);
