INSERT INTO program (name, school) VALUES
('Bachelor of Arts - Non Quota', 6),
('Bachelor of Arts in Applied Ethics and Management', 6),
('Bachelor of Arts in Archaeology', 6),
('Bachelor of Arts in Child, Youth, and Family Studies', 6),
('Bachelor of Arts in Community Development and Social Welfare', 6),
('Bachelor of Arts in Criminology and Security Studies', 6),
('Bachelor of Arts in Demography', 6),
('Bachelor of Arts in Development Studies', 6),
('Bachelor of Arts in Economics', 6),
('Bachelor of Arts in English Language and Linguistics', 6),
('Bachelor of Arts in French', 6),
('Bachelor of Arts in Gender Studies', 6),
('Bachelor of Arts in History', 6),
('Bachelor of Arts in Human Resource Management', 6),
('Bachelor of Arts in International Relations', 6),
('Bachelor of Arts in Intangible Cultural Heritage', 6),
('Bachelor of Arts in Linguistics and Chinese', 6),
('Bachelor of Arts in Linguistics and African Languages', 6),
('Bachelor of Arts in Local Government Administration', 6),
('Bachelor of Arts in Migration Studies', 6),
('Bachelor of Arts in Peace, Security and Conflict Resolution', 6),
('Bachelor of Arts in Philosophy and Applied Ethics', 6),
('Bachelor of Arts in Political Science', 6),
('Bachelor of Arts in Police and Security Studies', 6),
('Bachelor of Arts in Psychology', 6),
('Bachelor of Arts in Public Administration', 6),
('Bachelor of Arts in Project Management', 6),
('Bachelor of Arts in Sociology', 6),
('Bachelor of Business Management', 6),
('Bachelor of Communication Science', 6),
('Bachelor of Industrial Sociology and Labour Studies', 6),
('Bachelor of Media and Mass Communication', 6),
('Bachelor of Media and Journalism Studies', 6),
('Bachelor of Public Relations and Advertising', 6),
('Bachelor of Social Work', 6);
