INSERT INTO school (name) VALUES
	('Agricultural Sciences'),
	('Education'),
	('Engineering'),
	('Graduate School of Business'),
	('Health Sciences'),
	('Humanities and Social Sciences'),
	('Law'),
	('Medicine'),
	('Mines'),
	('Natural Sciences'),
	('Nursing Sciences'),
	('Public Health'),
	('Veterinary Medicine')
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Agricultural Sciences (Plant Sciences)', 1),
	('Bachelor of Agricultural Sciences (Land Management)', 1),
	('Bachelor of Agricultural Sciences (Animal Sciences)', 1),
	('Bachelor of Agricultural Sciences (Aquaculture)', 1),
	('Bachelor of Food Science And Technology', 1),
	('Bachelor of Science in Agricultural Extension', 1),
	('Bachelor of Science in Agricultural Economics', 1),
	('Bachelor of Science in Agronomy', 1),
	('Bachelor of Science in Human Nutrition', 1)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Adult Education', 2),
	('Bachelor of Agricultural Science with Education', 2),
	('Bachelor of Arts in Records and Archives Management (Baram)', 2),
	('Bachelor of Arts with Education', 2),
	('Bachelor of Arts with Education in Zambian Cultures and Ceremonies', 2),
	('Bachelor of Arts with Library and Information Studies', 2),
	('Bachelor of Community Empowerment Education', 2),
	('Bachelor of Cultural Studies', 2),
	('Bachelor of Education (Early Childhood Education)', 2),
	('Bachelor of Education (Educational Administration and Management)', 2),
	('Bachelor of Education (Educational Administration and Management): 3rd Year Entry', 2),
	('Bachelor of Education (Educational Psychology)', 2),
	('Bachelor of Education (Environmental Education and Management)', 2),
	('Bachelor of Education (Guidance and Counselling)', 2),
	('Bachelor of Education (Literacy and Language)', 2),
	('Bachelor of Education (Primary Education)', 2),
	('Bachelor of Education (Social Sciences)', 2),
	('Bachelor of Education (Sociology of Education)', 2),
	('Bachelor of Education (Special Education): 1st Year Entry', 2),
	('Bachelor of Education (Special Education): 3rd Year Entry', 2),
	('Bachelor of Education in Chinese Language Teaching', 2),
	('Bachelor of Education in Commerce and Entrepreneurship', 2),
	('Bachelor of Education-Secondary (Mathematics and Science)', 2),
	('Bachelor of Information and Communication Technologies in Education', 2),
	('Bachelor of Science with Education', 2),
	('Bachelor of Youth Development and Leadership', 2),
	('Diploma in ICTs For In-Service Teachers', 2)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Engineering - Agricultural', 3),
	('Bachelor of Engineering - Civil and Environmental', 3),
	('Bachelor of Engineering - Electrical', 3),
	('Bachelor of Engineering - Geomatic', 3),
	('Bachelor of Engineering - Mechanical', 3)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Science in Accounting and Finance', 4),
	('Bachelor of Science in Business Management', 4),
	('Bachelor of Science in Entrepreneurship and Innovation Management', 4),
	('Bachelor of Science in Human Resource Management', 4),
	('Bachelor of Science in Marketing', 4),
	('Bachelor of Science in Logistics and Transport Management', 4)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Pharmacy', 5),
	('Bachelor of Science in Biomedical Sciences', 5),
	('Bachelor of Science in Physiotherapy', 5),
	('Bachelor of Science in Radiography', 5),
	('Bachelor of Science in Prosthetics and Orthotics', 5)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Arts - Non Quota', 6),
	('Bachelor of Arts in Applied Ethics and Management', 6),
	('Bachelor of Arts in Archaeology', 6),
	('Bachelor of Arts in Child, Youth, and Family Studies', 6),
	('Bachelor of Arts in Community Development and Social Welfare', 6),
	('Bachelor of Arts in Criminology and Security Studies', 6),
	('Bachelor of Arts in Demography', 6),
	('Bachelor of Arts in Development Studies', 6),
	('Bachelor of Arts in Economics', 6),
	('Bachelor of Arts in English Language and Linguistics', 6),
	('Bachelor of Arts in French', 6),
	('Bachelor of Arts in Gender Studies', 6),
	('Bachelor of Arts in History', 6),
	('Bachelor of Arts in Human Resource Management', 6),
	('Bachelor of Arts in International Relations', 6),
	('Bachelor of Arts in Intangible Cultural Heritage', 6),
	('Bachelor of Arts in Linguistics and Chinese', 6),
	('Bachelor of Arts in Linguistics and African Languages', 6),
	('Bachelor of Arts in Local Government Administration', 6),
	('Bachelor of Arts in Migration Studies', 6),
	('Bachelor of Arts in Peace, Security and Conflict Resolution', 6),
	('Bachelor of Arts in Philosophy and Applied Ethics', 6),
	('Bachelor of Arts in Political Science', 6),
	('Bachelor of Arts in Police and Security Studies', 6),
	('Bachelor of Arts in Psychology', 6),
	('Bachelor of Arts in Public Administration', 6),
	('Bachelor of Arts in Project Management', 6),
	('Bachelor of Arts in Sociology', 6),
	('Bachelor of Business Management', 6),
	('Bachelor of Communication Science', 6),
	('Bachelor of Industrial Sociology and Labour Studies', 6),
	('Bachelor of Media and Mass Communication', 6),
	('Bachelor of Media and Journalism Studies', 6),
	('Bachelor of Public Relations and Advertising', 6),
	('Bachelor of Social Work', 6)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Law', 7),
	('Bachelor of Law - Distance Learning', 7)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Medicine and Surgery', 8),
	('Bachelor of Science in Clinical Medicine for Clinical Officers', 8)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Mineral Sciences in Geology', 9),
	('Bachelor of Engineering in Mining Engineering', 9),
	('Bachelor of Engineering in Geotechnical Engineering', 9),
	('Bachelor of Engineering in Metallurgical Engineering', 9)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Science - Non Quota', 10),
	('Bachelor of Science in Biology', 10),
	('Bachelor of Science in Chemistry', 10),
	('Bachelor of Science in Computer Science', 10),
	('Bachelor of Science in Ecology and Wildlife Management', 10),
	('Bachelor of Science in Entomology', 10),
	('Bachelor of Science in Environment and Natural Resources Management', 10),
	('Bachelor of Science in Molecular Biology and Genetics', 10),
	('Bachelor of Science in Mycology and Plant Pathology', 10),
	('Bachelor of Science in Microbiology', 10),
	('Bachelor of Science in Mathematics', 10),
	('Bachelor of Science in Physics', 10),
	('Bachelor of Science in Parasitology', 10)
;

INSERT INTO program (name, school) VALUES
	('Diploma in Registered Nursing (Kitwe Campus)', 11),
	('Diploma in Midwifery (Kitwe Campus)', 11),
	('Bachelor of Science in Nursing', 11),
	('Bachelor of Science in Midwifery', 11),
	('Bachelor of Science in Oncology Nursing', 11),
	('Bachelor of Science in Mental Health and Psychiatric Nursing', 11),
	('Bachelor of Science in Public Health Nursing', 11)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Science in Environmental Health', 12),
	('Bachelor of Health Promotion', 12),
	('Bachelor of Science in Public Health', 12),
	('Bachelor of Science in Health Services Management and Planning', 12)
;

INSERT INTO program (name, school) VALUES
	('Bachelor of Veterinary Medicine', 13)
;
INSERT INTO country (name) VALUES
    ('Afghanistan'),
    ('Albania'),
    ('Algeria'),
    ('Andorra'),
    ('Angola'),
    ('Antigua and Barbuda'),
    ('Argentina'),
    ('Armenia'),
    ('Australia'),
    ('Austria'),
    ('Azerbaijan'),
    ('Bahamas'),
    ('Bahrain'),
    ('Bangladesh'),
    ('Barbados'),
    ('Belarus'),
    ('Belgium'),
    ('Belize'),
    ('Benin'),
    ('Bhutan'),
    ('Bolivia'),
    ('Bosnia and Herzegovina'),
    ('Botswana'),
    ('Brazil'),
    ('Brunei'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Cabo Verde'),
    ('Cambodia'),
    ('Cameroon'),
    ('Canada'),
    ('Central African Republic'),
    ('Chad'),
    ('Chile'),
    ('China'),
    ('Colombia'),
    ('Comoros'),
    ('Congo, Democratic Republic of the'),
    ('Congo, Republic of the'),
    ('Costa Rica'),
    ('Croatia'),
    ('Cuba'),
    ('Cyprus'),
    ('Czech Republic'),
    ('Denmark'),
    ('Djibouti'),
    ('Dominica'),
    ('Dominican Republic'),
    ('Ecuador'),
    ('Egypt'),
    ('El Salvador'),
    ('Equatorial Guinea'),
    ('Eritrea'),
    ('Estonia'),
    ('Eswatini'),
    ('Ethiopia'),
    ('Fiji'),
    ('Finland'),
    ('France'),
    ('Gabon'),
    ('Gambia'),
    ('Georgia'),
    ('Germany'),
    ('Ghana'),
    ('Greece'),
    ('Grenada'),
    ('Guatemala'),
    ('Guinea'),
    ('Guinea-Bissau'),
    ('Guyana'),
    ('Haiti'),
    ('Honduras'),
    ('Hungary'),
    ('Iceland'),
    ('India'),
    ('Indonesia'),
    ('Iran'),
    ('Iraq'),
    ('Ireland'),
    ('Israel'),
    ('Italy'),
    ('Jamaica'),
    ('Japan'),
    ('Jordan'),
    ('Kazakhstan'),
    ('Kenya'),
    ('Kiribati'),
    ('Korea, North'),
    ('Korea, South'),
    ('Kuwait'),
    ('Kyrgyzstan'),
    ('Laos'),
    ('Latvia'),
    ('Lebanon'),
    ('Lesotho'),
    ('Liberia'),
    ('Libya'),
    ('Liechtenstein'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Madagascar'),
    ('Malawi'),
    ('Malaysia'),
    ('Maldives'),
    ('Mali'),
    ('Malta'),
    ('Marshall Islands'),
    ('Mauritania'),
    ('Mauritius'),
    ('Mexico'),
    ('Micronesia'),
    ('Moldova'),
    ('Monaco'),
    ('Mongolia'),
    ('Montenegro'),
    ('Morocco'),
    ('Mozambique'),
    ('Myanmar'),
    ('Namibia'),
    ('Nauru'),
    ('Nepal'),
    ('Netherlands'),
    ('New Zealand'),
    ('Nicaragua'),
    ('Niger'),
    ('Nigeria'),
    ('North Macedonia'),
    ('Norway'),
    ('Oman'),
    ('Pakistan'),
    ('Palau'),
    ('Palestine'),
    ('Panama'),
    ('Papua New Guinea'),
    ('Paraguay'),
    ('Peru'),
    ('Philippines'),
    ('Poland'),
    ('Portugal'),
    ('Qatar'),
    ('Romania'),
    ('Russia'),
    ('Rwanda'),
    ('Saint Kitts and Nevis'),
    ('Saint Lucia'),
    ('Saint Vincent and the Grenadines'),
    ('Samoa'),
    ('San Marino'),
    ('Sao Tome and Principe'),
    ('Saudi Arabia'),
    ('Senegal'),
    ('Serbia'),
    ('Seychelles'),
    ('Sierra Leone'),
    ('Singapore'),
    ('Slovakia'),
    ('Slovenia'),
    ('Solomon Islands'),
    ('Somalia'),
    ('South Africa'),
    ('South Sudan'),
    ('Spain'),
    ('Sri Lanka'),
    ('Sudan'),
    ('Suriname'),
    ('Sweden'),
    ('Switzerland'),
    ('Syria'),
    ('Taiwan'),
    ('Tajikistan'),
    ('Tanzania'),
    ('Thailand'),
    ('Togo'),
    ('Tonga'),
    ('Trinidad and Tobago'),
    ('Tunisia'),
    ('Turkey'),
    ('Turkmenistan'),
    ('Tuvalu'),
    ('Uganda'),
    ('Ukraine'),
    ('United Arab Emirates'),
    ('United Kingdom'),
    ('United States'),
    ('Uruguay'),
    ('Uzbekistan'),
    ('Vanuatu'),
    ('Vatican City'),
    ('Venezuela'),
    ('Vietnam'),
    ('Yemen'),
    ('Zimbabwe')
;

INSERT into staff VALUES(
   1,
   "1",
   "Nelson",
   "Musonda",
   "Male"
);
INSERT into staff VALUES(
   2,
   "2",
   "Arnold",
   "Makonye",
   "Male"
);

INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   1,
   "1",
   "Arnold",
   "Makonye",
   "Male",
   103,
   1
);
INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   2,
   "2",
   "Mercy",
   "Namfukwe",
   "Female",
   56,
   10
);
INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   3,
   "3",
   "Christabel",
   "Kunda",
   "Female",
   103,
   50
);
INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   4,
   "4",
   "Mwiche",
   "Nakamba",
   "Female",
   13,
   67
);
INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   5,
   "5",
   "Akakandelwa",
   "Akakandelwa",
   "Male",
   45,
   53
);


INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   6,
   "6",
   "Twaambo",
   "Mudenda",
   "Male",
   45,
   53
);
INSERT into student (id, password, f_name, l_name, sex, program, country) VALUES(
   7,
   "7",
   "Jane",
   "Yowela",
   "Male",
   45,
   53
);
